### ISSUE TITLE
Documentation errors

### ISSUE THREAD

**Issue by jamolkhon** [nhaarman/Acorn#115]
In Scenes section
> **‘started’** : The Scene is dormant, waiting to be started or to be destroyed.
> **‘stopped’** : The Scene is started.

In Navigators section:
> During the lifetime of a Navigator it can go from **‘inactive’ to ‘inactive’** and vice versa multiple times, until it reaches the ‘destroyed’ state.

In Usage section:

> Acorn is tactically divided in several modules to be able to separate different concerns from **eachother**.

**Comment by jamolkhon** [comment]
I'm sorry I cannot create a pull request at the moment.

**Comment by nhaarman** [comment]
Thanks! No problem, I will update them :+1:

**Comment by nhaarman** [comment]
Fixed!
