### ISSUE TITLE
Arrow Dependency in acorn-ext module

### ISSUE THREAD

**Issue by gumil** [nhaarman/acorn#153]
Arrow seems an unnecessary dependency on the acorn-ext module https://github.com/nhaarman/acorn/blob/bcb8f98e83b81bd83f4ebd767a743334716cf9da/ext/acorn/build.gradle#L13

Tested by running `./gradlew test` on the root project.

Is there a reason to have the arrow dependency here?

**Comment by nhaarman** [comment]
Hm, that's interesting. Its last change is the initial commit, so I guess that's from before the `rx` module was split off from the core modules. 
Running `./gradlew assemble` should result in failures: the rx module _does_ need Arrow.
