### ISSUE TITLE
Intercepts the controller view when it's immediately added to the root ViewGroup

### ISSUE THREAD

**Issue by manueldidonna** [nhaarman/acorn#171]
I need to modify all the controller views before they are added to the root ViewGroup, but I haven't find any way to intercepts the ViewController when it's attached without a transition

**Comment by VincentJian** [comment]
There is a extension function [SceneTransition.doOnStart](https://github.com/nhaarman/acorn/blob/1.x/ext/acorn-android/src/main/java/com/nhaarman/acorn/android/transition/DoBeforeTransition.kt). If this extension does not suit your requirement, then you need custom SceneTransition.
